version: "2"
name: sdffs
canonical: sdffs
author: Belen Gonzalez
status: private
description: dsadsaasd
image: ""
keywords:
- sdaasdasd
- provider:aws
technologies:
- technology: stackcraft
  version: "1"
dependencies:
- ref: seraf:infra-amazon-elk
  required: true
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      sdffs:
        destination: ($ project $)/default/terraform/($ environment $)/sdffs.tf
        path: default/terraform/sdffs.tf.sample
