version: "2"
name: abcne9i0oiueoiu
canonical: abcne9i0oiueoiu
author: belen_gonzalez
status: private
description: fffff
image: ""
keywords:
- afk
- provider:aws
technologies: []
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: pipeline/default/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: pipeline/default/variables.sample.yaml
