---
version: '2'
# Configuration of the Cycloid stack
name: 'Bugged stack'
canonical: 'bugged-stack'
status: 'private'
description: 'A stack with syntax errors. For debugging purpose only.'
keywords:
  - 'debug'
  - 'bugged'
author: 'Thomas-lhuillier'
image: 'https://image.flaticon.com/icons/svg/269/269064.svg'

config:
  default:
    name: 'Default pipeline'
    description: 'This is a pipeline description, necessary to let the user which pipeline to use.'
    pipeline:
      pipeline:
        path: 'pipeline/default/test.yml'
      variables:
        path: 'pipeline/default/variables.sample.yml'
      empty:
        path: 'pipeline/default/empty.yml'
