version: "2"
name: tl-test-blank
canonical: tl-test-blank
author: thomas_lhuillier
status: private
description: The bare minimum files to build your stack from scratch.
image: https://raw.githubusercontent.com/Thomas-lhuillier/catalog-repo/templates/blank-sample/thumbnail.png
keywords: []
template: false
technologies: []
dependencies: []
config:
    default:
        name: Default
        pipeline:
            pipeline:
                path: pipeline/pipeline.yml
            variables:
                destination: ($ project $)/pipeline/variables-($ environment $).yml
                path: pipeline/variables.sample.yml
