# Use the latest version 2 of the Cycloid stack engine.
version: 2
name: acme-stack
canonical: acme-stack
author: 'thomas_lhuillier'
# Fill in the stack details.
description: 'Discover how to integrate Terraform in your pipelines.'
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
keywords:
  - 'terraform'
  - 'vanilla'
technologies:
  - technology: terraform
    version: 1.3.9
template: false
status: 'private'
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  vanilla:
    name: 'Basic Terraform'
    description: 'Cloud-agnostic Terraform sample with no specific provider integration.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
