# Use the latest version 2 of the Cycloid stack engine.
version: 2
name: acme-stack
canonical: acme-stack
author: 'thomas_lhuillier'
# Fill in the stack details.
description: 'CI/CD for the Acme app.'
image: https://github.com/Thomas-lhuillier/catalog-repo/blob/stacks/acme-stack/thumbnail.png?raw=true
keywords:
  - 'terraform'
  - 'vanilla'
technologies:
  - technology: terraform
    version: 1.3.9
template: false
status: 'private'
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  production:
    name: 'Production'
    description: 'Full featured auto scaling infrastructure for production like environments.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
  develop:
    name: 'Develop'
    description: 'Minimal infrastructure running code with debug flags on.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ project $)/terraform/($ environment $)/main.tf'
