version: '4'
name: Fake terraform
canonical: fake-terraform
author: 'thomas_lhuillier'
description: 'A stack provisioning fake terraform resources.'
image: https://i.imgur.com/Pw8RjK5.png
keywords:
  - 'terraform'
  - 'fake'
  - 'debug'
technologies:
  - technology: terraform
    version: 1.8.2
template: false
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  vanilla:
    name: 'Basic Terraform'
    description: 'Cloud-agnostic Terraform sample with no specific provider integration.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
    terraform:
      main:
        path: 'terraform/main.tf.sample'
        destination: '($ .config_root $)/terraform/main.tf'
