# Configuration of the CI pipeline
version: '2'
name: 'TL Magento (forms)'
canonical: 'stack-tl-magento-forms'
description: 'A stack with 1 pipeline. Packed with forms content.'
keywords:
  - 'stack'
  - 'test'
  - 'forms'
author: 'Thomas L'huillier'
image: 'https://cdn2.iconfinder.com/data/icons/online-survey-1/66/22-512.png'
type: 'stack'
config:
  default:
    name: 'Default pipeline'
    description: 'This is a pipeline description, necessary to let the user which pipeline to use.'
    pipeline:
      pipeline:
        path: 'default/pipeline/magento.yml'
      variables:
        destination: ($ project $)/default/pipeline/variables-($ environment $).yml
        path: 'default/pipeline/variables.sample.yml'

    # Configuration of terraform to setup the infrastructure
    terraform:
      magento:
        path: 'default/terraform/magento.tf.sample'
        destination: '($ project $)/default/terraform/magento/($ environment $)/magento.tf'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'default/ansible/environments/front.yml.sample'
        destination: '($ project $)/default/environments/($ environment $)-front.yml'

