---
default:
  pipeline:
    AWS:
      - name: "Default Region"
        key: aws_default_region
        type: string
        widget: dropdown
        description: "In which region you would like your project to run"
        default: "eu-west-1"
        values: ["eu-west-1", "eu-west-2", "eu-west3", "eu-south1", "eu-north1", "eu-central1"]
        required: false
      - name: "S3 Bucket"
        key: terraform_storage_bucket_name
        type: string
        widget: simple_text
        description: "The S3 bucket where terraform will store its tfstate"
        default: "($ organization_canonical $)-terraform-remote-state"
        required: true
    Git:
      - name: "Service catalog repository"
        key: sc_repository
        widget: cy_scs
        type: string
        description: "The service catalog repository"
        default: "git@github.com:cycloidio/cycloid-stacks-test.git"
        required: true
      - name: "Service catalog credentials"
        key: sc_git_key
        widget: cy_cred
        type: string
        description: "The credential used to access the service catalog"
        default: "((ssh_readonly.ssh_key))"
        required: false
      - name: "Service catalog path"
        key: sc_path
        type: string
        widget: simple_text
        description: "The path of the stack in the service catalog"
        default: "8-wordpress-demo"
        required: false
      - name: "Service catalog branch"
        key: sc_branch
        widget: cy_branch
        type: string
        description: "The branch used by the service catalog"
        source: sc_repository
        default: "stacks"
        required: true
      - name: "Config repository"
        key: config_git_repository
        type: string
        widget: cy_crs
        description: "The config repository to save configurations"
        default: "git@github.com:cycloidio/cycloid-stacks-test.git"
        required: true
      - name: "Config repository credentials"
        key: config_git_key
        type: string
        widget: cy_cred
        default: "((ssh_readonly.ssh_key))"
        required: false
      - name: "Config repository branch"
        key: config_git_branch
        widget: cy_branch
        type: string
        description: "The branch used by the config repository"
        source: config_git_repository
        default: "config"
        required: false
      - name: "Config repository path"
        key: config_terraform_path
        widget: simple_text
        type: string
        description: "The path in which the config will be saved"
        default: "cycloid-wordpress-demo/terraform"
        required: false
