---
version: '2'
# Configuration of the Cycloid stack
name: 'Debug-fe'
canonical: 'tl-stack-dummy'
status: 'public'
description: |
  This stack is a dummy stack which helps debugging when working on the front-end.
keywords:
  - 'debug'
  - 'dummy'
author: 'Thomas'
image: |
  https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ24fdonx171ZNyuPDty7fjVfnr1pN7qMbh5w&usqp=CAU
technologies:
  - technology: concourse
    version: n/a
  - technology: busybox
    version: n/a

config:
  default:
    name: 'Default'
    description: 'Default debug pipeline'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  worker:
    name: 'Local worker'
    description: 'Debug pipeline running on a tagged worker'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-tagged-worker.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
