---
# Configuration of the Cycloid stack
version: '2'
name: 'k8s-runner'
canonical: 'tl-stack-k8s-cp'
status: 'public'
description: |
  A test stack with cloud provider key on use-cases
keywords:
  - 'kubernetes'
  - 'eks'
  - 'gke'
  - 'onprem'
  - 'terraform'
  - 'provider:aws'
  - 'provider:gcp'
  - 'provider:scw'
author: 'Cycloid'
image: |
  https://avatars3.githubusercontent.com/u/22258569?s=400&v=4
technologies:
  - technology: Kubernetes
    version: n/a

config:
  default:
    name: 'Classic Kubernetes'
    description: 'For on-premises style Kubernetes clusters.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  default_terraform:
    name: 'Classic Kubernetes + Terraform'
    description: 'For on-premises style Kubernetes clusters + terraform code.'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-terraform.yml'
      variables:
        path: 'pipeline/variables-terraform.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  eks:
    name: 'Amazon EKS'
    description: 'For AWS Elastic Kubernetes Service clusters.'
    cloud_provider: 'aws'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-eks.yml'
      variables:
        path: 'pipeline/variables-eks.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  eks_terraform:
    name: 'Amazon EKS + Terraform'
    description: 'For AWS Elastic Kubernetes Service clusters + terraform code.'
    cloud_provider: 'aws'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-eks-terraform.yml'
      variables:
        path: 'pipeline/variables-eks-terraform.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  gke:
    name: 'Google GKE'
    description: 'For Google Kubernetes Engine clusters.'
    cloud_provider: 'google'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-gke.yml'
      variables:
        path: 'pipeline/variables-gke.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
  gke_terraform:
    name: 'Google GKE + Terraform'
    description: 'For Google Kubernetes Engine clusters + terraform code.'
    cloud_provider: 'google'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline-gke-terraform.yml'
      variables:
        path: 'pipeline/variables-gke-terraform.sample.yml'
        destination: '($ project $)/pipeline/variables-($ environment $).yml'
