version: v2
name: tralala
canonical: 1-tralala
author: Thomas Lhuillier
description: tralala
type: stack
image: ""
keywords:
- tralala
- provider:flexibleengine
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        path: default/pipeline/variables.sample.yaml
