# Use the latest version 2 of the Cycloid stack engine.
version: 4
name: Debug forms
canonical: tl-forms
author: 'thomas_lhuillier'
# Fill in the stack details.
description: 'Renders a wide variety of forms widgets and options.'
image: https://i.imgur.com/UdU5CKY.png
template: false
# Add use cases to the stack.
# See: https://docs.cycloid.io/manage/pipeline/multi-use-case.html#multiple-use-case
config:
  default:
    name: 'Default'
    pipeline:
      pipeline:
        path: 'pipeline/pipeline.yml'
      variables:
        path: 'pipeline/variables.sample.yml'
        destination: '($ .config_root $)/pipeline/variables.yml'
