use_cases:
- name: default
  sections:
  - name: Application
    groups:
    - name: Configuration
      technologies: [ansible]
      vars:
      - name: Enable conditional fields
        key: enable_cond
        widget: switch
        type: boolean
        default: false
    - name: Advanced configuration
      technologies: [ansible]
      condition: '$enable_cond == true'
      vars:
      - name: Required conditional value
        key: required_cond_value
        widget: simple_text
        type: string
        required: true
