version: "2"
name: tl-test-ref
canonical: tl-test-ref
author: Thomas lhuillier
status: private
description: another test
image: ""
keywords:
- test
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      tl-test-ref:
        destination: ($ project $)/default/terraform/($ environment $)/tl-test-ref.tf
        path: default/terraform/tl-test-ref.tf.sample
