version: '2'

use_cases:

  - name: worker
    sections:
      - name: pipeline
        groups:
          - name: worker
            technologies: [pipeline]
            vars:
              - key: worker_tag
                name: Worker tag
                type: string
                widget: simple_text
                default:
                description: |
                  The tags by which to match workers. The jobs will run on workers that match the given tags. Leave it empty to use non tagged workers.
                  Check the stack README for guidance on how to run a local worker.

  - name: aws
    sections: []

  - name: google
    sections: []

  - name: azure
    sections: []

  - name: vmware
    sections: []

  - name: fe
    sections: []

  - name: scaleway
    sections: []

  - name: ovh
    sections: []

  - name: alibaba
    sections: []

  - name: oracle
    sections: []
