.definitions:
  sections:
    - section: &tagged-worker
        name: worker
        groups:
          - name: worker
            technologies: [pipeline]
            vars:
              - key: worker_tag
                name: Worker tag
                type: string
                widget: simple_text
                default:
                description: |
                  The tags by which to match workers. The jobs will run on workers that match the given tags. Leave it empty to use non tagged workers.
                  Check the stack README for guidance on how to run a local worker.
version: '2'
use_cases:
  - name: debug-pipeline
    sections:
      - *tagged-worker
  - name: debug-stackforms
    sections:
      - name: section
        groups:
          - name: group
            technologies: [pipeline]
            vars:
            - name: "auto_complete"
              description: |
                  Only `string` allowed.
                  Values listed here are suggestions, user can input arbitrary values.
              key: "auto_complete_var"
              widget: "auto_complete"
              type: "string"
              values:
              - "one value"
              - "another one"
              - "maybe"
            - name: "dropdown"
              description: |
                  Type can be anything but raw
                  Must have at least 1 value, only 2 if `boolean`
              key: "dropdown_var"
              widget: "dropdown"
              type: "string"
              values:
              - "value1"
              - "value2"
              - "value3"
            - name: "number"
              description: "Type can be `integer` of `float`"
              key: "number_var"
              widget: "number"
              type: "integer"
              default: 42
            - name: "radios"
              description: |
                Type can be anything but `raw`
                Must have at least 1 value, only 2 if `boolean`
              key: "radios_var"
              widget: "radios"
              type: "boolean"
              values:
              - true
              - false
            - name: "simple_text"
              description: "Only `string` allowed"
              key: "simple_text_var"
              widget: "simple_text"
              type: "string"
              default: |
                Some text value
            - name: "slider_list"
              description: |
                Type can be `string`, `map`, `boolean` or `integer`.
                Must have at least 1 value, only 2 if `boolean`
                Values of type `map` will be redered as
                `JSON`, `YAML` or `HCL`
                depending on the technologies used.
              key: "slider_list_var"
              widget: "slider_list"
              type: "string"
              values:
              - "one"
              - "two"
              - "three"
            - name: "slider_range"
              description: |
                Type can be only `integer`
                Only two values accepted, minimal value first, maximum second.
              key: "slider_range_var"
              widget: "slider_range"
              type: "integer"
              values:
              - 24 # min
              - 48 # max
            - name: "switch"
              description: "Type can be only `boolean`"
              key: "switch_var"
              widget: "switch"
              type: "boolean"
            - name: "text_area"
              description: "Type can be anything, `raw` included."
              key: "text_area_var"
              widget: "text_area"
              type: "map"
            - name: "cy_inventory_resource"
              description: "Select a resource attribute from the inventory and link the value to this asset"
              key: "cy_inventory_resource_var"
              type: "string"
              widget: "cy_inventory_resource"
              widget_config:
                attribute: "id"
                filters:
                  attributes: 'tags.env[eq]=infra'
                  type: "aws_vpc"
      - *tagged-worker
  - name: aws
    sections:
      - *tagged-worker
  - name: google
    sections:
      - *tagged-worker
  - name: azure
    sections:
      - *tagged-worker
  - name: vmware
    sections:
      - *tagged-worker
  - name: fe
    sections:
      - *tagged-worker
  - name: scaleway
    sections:
      - *tagged-worker
  - name: ovh
    sections:
      - *tagged-worker
  - name: alibaba
    sections:
      - *tagged-worker
  - name: oracle
    sections:
      - *tagged-worker
