version: "2"
name: nikola-stack-dep-test
canonical: nikola-stack-dep-test
author: Nikola Savanovic
status: private
description: testing creation of the stack with added other stacks as dependencies
image: ""
keywords:
- testing
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies:
- ref: seraf:stack-dummy
  required: true
- ref: seraf:stack-golang
  required: true
- ref: seraf:dan_stack
  required: true
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
