# Configuration of the CI pipeline
name: 'Stack Magento2'
canonical: 'stack-magento2'
description: 'A stack with a single pipeline using config version 1'
keywords:
  - 'stack'
  - 'public'
author: 'gaelL'
image: 'https://picsum.photos/140/140'
type: 'stack'
config:
  pipeline:
    pipeline:
      path: 'pipeline/magento.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of ansible for provisionning
  ansible:
    magento:
      path: 'ansible/environments/front.yml.sample'
      destination: 'ansible/environments/($ environment $)-front.yml'

  # Configuration of terraform to setup the infrastructure    
  terraform:
    magento:
      path: 'terraform/magento.tf.sample'
      destination: 'terraform/magento/($ environment $)/magento.tf'
