# YAML anchors
shared:
  - &task-merge-stack-and-config
    task: merge-stack-and-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cycloid/cycloid-toolkit
          tag: latest
      run:
        path: /usr/bin/merge-stack-and-config
      inputs:
        - name: git_config
          path: "config"
        - name: git_stack
          path: "stack"
      outputs:
        - name: merged-stack
          path: "merged-stack"
    params:
      CONFIG_PATH: ((project))/terraform/((env))
      STACK_PATH: ((stack_path))/terraform

groups:
- name: overview
  jobs:
  - terraform-plan
  - terraform-apply
- name: destroy
  jobs:
  - terraform-destroy

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: cycloid/terraform-resource
    tag: '1.3.9'

resources:
# The Terraform Concourse resource to manage infrastructure via Terraform.
# See https://github.com/ljfranklin/terraform-resource#source-configuration
- name: tfstate
  type: terraform
  icon: terraform
  source:
    backend_type: http # Required. The name of the Terraform backend the resource will use to store statefiles, e.g. http or s3.
    backend_config: # Required. A map of key-value configuration options specific to your choosen backend.
      address: '((cycloid_api_url))/inventory?jwt=($ inventory_jwt $)'
      skip_cert_verification: true
    env_name: ((env)) # Optional. Name of the environment to manage, e.g. staging. A Terraform workspace will be created with this name.
    vars: # Optional. A collection of Terraform input variables. These are typically used to specify credentials or override default module values.
      env: ((env))
      project: ((project))
      organization: ((org))
      gcp_project: ((gcp_project))
      gcp_zone: ((gcp_zone))
    env: # Optional. Similar to vars, this collection of key-value pairs can be used to pass environment variables to Terraform.
      GOOGLE_PROJECT: ((gcp_project))
      GOOGLE_ZONE: ((gcp_zone))
      GOOGLE_CREDENTIALS: ((gcp_credentials_json))

# The Terraform stack (will be merged with the config).
- name: git_stack
  type: git
  icon: github-circle
  source:
    uri: ($ scs_url $)
    branch: ($ scs_branch $)
    private_key: ((stack_git_private_key))
    paths:
      - ((stack_path))/terraform/*

# The Terraform config (will be merged with the stack).
- name: git_config
  type: git
  icon: github-circle
  source:
    uri: ($ cr_url $)
    branch: ($ cr_branch $)
    private_key: ((config_git_private_key))
    paths:
      - ((project))/terraform/((env))/*

jobs:
  - name: terraform-plan
    serial: true
    serial_groups: [terraform]
    max_in_flight: 1
    build_logs_to_retain: 10
    plan:
      - do:
        - get: git_stack
          trigger: true
        - get: git_config
          trigger: true
        - *task-merge-stack-and-config
        - put: tfstate
          params:
            plan_only: true
            terraform_source: merged-stack/

  - name: terraform-apply
    serial: true
    serial_groups: [terraform]
    build_logs_to_retain: 10
    plan:
      - do:
        - get: git_stack
          trigger: false
          passed:
            - terraform-plan
        - get: git_config
          trigger: false
          passed:
            - terraform-plan
        - get: tfstate
          trigger: false
          passed:
            - terraform-plan
        - *task-merge-stack-and-config
        - put: tfstate
          params:
            plan_run: true
            terraform_source: merged-stack/

  - name: terraform-destroy
    serial: true
    serial_groups: [terraform]
    build_logs_to_retain: 10
    plan:
      - do:
          - get: git_stack
            trigger: false
          - get: git_config
            trigger: false
          - *task-merge-stack-and-config
          - put: tfstate
            params:
              action: destroy
              terraform_source: merged-stack/
            get_params:
              action: destroy
