version: "2"
name: tl-del
canonical: tl-del
author: thomas_lhuillier
status: private
description: Discover how to integrate Terraform in your pipelines.
image: https://raw.githubusercontent.com/Thomas-lhuillier/catalog-repo/templates/terraform-sample/thumbnail.png
keywords:
    - terraform
    - vanilla
template: false
technologies:
    - technology: terraform
      version: 1.3.9
dependencies: []
config:
    vanilla:
        description: Cloud-agnostic Terraform sample with no specific provider integration.
        name: Basic Terraform
        pipeline:
            pipeline:
                path: pipeline/pipeline.yml
            variables:
                destination: ($ project $)/pipeline/variables-($ environment $).yml
                path: pipeline/variables.sample.yml
        terraform:
            main:
                destination: ($ project $)/terraform/($ environment $)/main.tf
                path: terraform/main.tf.sample
