# Use the latest version 2 of the Cycloid StackForms engine.
version: 2

# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
- name: vanilla
  sections:
  - name: Cloud provider
    groups:

  - name: App
    groups:
    - name: config
      technologies: [terraform]
      vars:
      - name: "Instance type"
        description: "Specify the size of the instance"
        key: instance_type
        type: string
        widget: auto_complete
        values: ["micro", "small", "medium", "large"]
        default: "medium"

  - name: Git
    groups:
    - name: config
      technologies: [pipeline]
      vars:
      - name: "Config git key"
        description: "SSH key pair to fetch the config Git repository."
        key: config_git_private_key
        type: string
        required: true
        widget: cy_cred
        widget_config:
          cred_types: [ssh]
    - name: stack
      technologies: [pipeline]
      vars:
      - name: "Stack git key"
        description: "SSH key pair to fetch the stack Git repository."
        key: stack_git_private_key
        type: string
        required: true
        widget: cy_cred
        widget_config:
          cred_types: [ssh]
