resources:
  - name: git-source-code
    type: git
    icon: github
    source:
      disable_ci_skip: false
      uri: https://github.com/Thomas-lhuillier/test-repo-trigger-ci.git
      branch: master

jobs:
- name: job-hello-world
  build_logs_to_retain: 50
  plan:
  - get: git-source-code
    trigger: true
  - task: random-failing
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          echo done
          exit $(($RANDOM%2))
  - in_parallel:
    - do:
      - task: random-failing
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: /bin/sh
            args:
            - -ec
            - |
              echo done
              exit $(($RANDOM%2))
      - try:
        - task: random-failing
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: /bin/sh
              args:
              - -ec
              - |
                echo done
                exit $(($RANDOM%2))
