jobs:
  - name: job-hello-world
    build_logs_to_retain: 50
    plan:
      - task: random-failing
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: /bin/sh
            args:
            - -ec
            - |
              echo done
              exit $(($RANDOM%2))
      - in_parallel:
        - task: random-failing
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: /bin/sh
              args:
              - -ec
              - |
                echo done
                exit $(($RANDOM%2))
        - task: random-failing
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: /bin/sh
              args:
              - -ec
              - |
                echo done
                exit $(($RANDOM%2))
      - do:
        - task: random-failing
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: /bin/sh
              args:
              - -ec
              - |
                echo done
                exit $(($RANDOM%2))
      - try:
          task: random-failing
          config:
            platform: linux
            image_resource:
              type: docker-image
              source: {repository: busybox}
            run:
              path: /bin/sh
              args:
              - -ec
              - |
                echo done
                exit $(($RANDOM%2))
