jobs:
- name: job-hello-world
  build_logs_to_retain: 50
  plan:
  - task: hello-world
    config:
        platform: linux
        image_resource:
            type: docker-image
            source: {repository: busybox}
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo ${MESSAGE}
            exit $(($RANDOM%2))
        params:
          MESSAGE: ((message))
