# Configuration of the CI pipeline
version: 'v2'
name: 'Stack Magento'
canonical: 'stack-magento-v2'
description: 'Description of the stack magento'
keywords:
  - 'stack'
  - 'public'
author: 'gaelL'
image: 'https://raw.githubusercontent.com/cycloid/test-psc/stack-magento/master/icon.png'
type: 'stack'
config:
  first-usecase:
    pipeline:
      pipeline:
        path: 'pipeline/first/magento.yml'
      variables:
        path: 'pipeline/first/variables.sample.yml'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'ansible/first/environments/front.yml.sample'
        destination: 'ansible/first/environments/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure    
    terraform:
      magento:
        path: 'terraform/first/magento.tf.sample'
        destination: 'terraform/first/magento/($ environment $)/magento.tf'
  second-usecase:
    pipeline:
      pipeline:
        path: 'pipeline/second/magento.yml'
      variables:
        path: 'pipeline/second/variables.sample.yml'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'ansible/second/environments/front.yml.sample'
        destination: 'ansible/second/environments/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure    
    terraform:
      magento:
        path: 'terraform/second/magento.tf.sample'
        destination: 'terraform/second/magento/($ environment $)/magento.tf'
