# Configuration of the CI pipeline
version: 'v2'
name: 'Stack Magento'
canonical: 'stack-magento-v2'
description: 'A stack with 2 pipelines'
keywords:
  - 'stack'
  - 'public'
author: 'gaelL'
image: 'https://www.freeiconspng.com/uploads/troll-face-png-9.png'
type: 'stack'
config:
  first-usecase:
    name: 'First pipeline'
    description: 'This is a pipeline description, necessary to let the user which pipeline to use.'
    pipeline:
      pipeline:
        path: 'pipeline/first/magento.yml'
      variables:
        path: 'pipeline/first/variables.sample.yml'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'ansible/first/environments/front.yml.sample'
        destination: 'ansible/first/environments/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure    
    terraform:
      magento:
        path: 'terraform/first/magento.tf.sample'
        destination: 'terraform/first/magento/($ environment $)/magento.tf'
  second-usecase:
    name: 'Second pipeline'
    description: 'This is another pipeline description, necessary to let the user which pipeline to use.'
    pipeline:
      pipeline:
        path: 'pipeline/second/magento.yml'
      variables:
        path: 'pipeline/second/variables.sample.yml'

    # Configuration of ansible for provisionning
    ansible:
      magento:
        path: 'ansible/second/environments/front.yml.sample'
        destination: 'ansible/second/environments/($ environment $)-front.yml'

    # Configuration of terraform to setup the infrastructure    
    terraform:
      magento:
        path: 'terraform/second/magento.tf.sample'
        destination: 'terraform/second/magento/($ environment $)/magento.tf'
