jobs:
- name: job-dummy
  build_logs_to_retain: 3
  plan:
  - task: dummy
    tags: [((worker_tag))]
    config:
        platform: linux
        image_resource:
            type: docker-image
            source: {repository: busybox}
        run:
          path: /bin/sh
          args:
          - -ec
          - |
            echo ,___,
              (O,O)
              /)_)
              ""
