jobs:
  - name: job-dummy
    build_logs_to_retain: 10
    plan:
      - task: dummy
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: busybox
          run:
            path: /bin/sh
            args:
              - '-ec'
              - |
                echo yolo
