version: "2"
name: aaa
canonical: aaa
author: Thomas lhuillier
status: private
description: aaa
image: ""
keywords:
- aaa
- provider:aws
- provider:vault
technologies:
- technology: stackcraft
  version: "1"
dependencies: []
config:
  default:
    description: ""
    name: default
    pipeline:
      pipeline:
        path: default/pipeline/terraform-pipeline.yaml
      variables:
        destination: ($ project $)/pipeline/variables-($ environment $).yml
        path: default/pipeline/variables.sample.yaml
    terraform:
      aaa:
        destination: ($ project $)/default/terraform/($ environment $)/aaa.tf
        path: default/terraform/aaa.tf.sample
